version: '3'

services:
  drone-server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    image: drone-server:latest
    ports:
      - 8080:8000
      - 9000:9000
    environment:
      # - GIN_MODE=release
      - DRONE_HOST=http://drone-server
      - DRONE_OPEN=true
      - DRONE_ADMIN=pi
      # github config options
      - DRONE_GITHUB=true
      - DRONE_GITHUB_URL=https://github.com
      # these are defined in ./github.secret
      # - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      # - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
    env_file:
      - ./drone_secret.secret
      - ./github.secret

  drone-agent:
    build:
      context: ./agent/
      dockerfile: Dockerfile
    image: drone-agent:latest
    environment:
      # - GIN_MODE=release
      - DRONE_SERVER=drone-server:9000
      - DRONE_MAX_PROCS=3
    env_file:
      - ./drone_secret.secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - drone-server
